# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlPvcmount < Formula
  desc "Go binary for temporary mounting of PVCs"
  homepage "https://github.com/Stenstromen/kubectl-pvcmount"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/Stenstromen/kubectl-pvcmount/releases/download/v1.0.0/kubectl-pvcmount_Darwin_x86_64.tar.gz"
      sha256 "6e0f5dcd9c6bda5e4d113ac65a7e2c20226d35d41d7194ff0325f6b5cc37d1f8"

      def install
        bin.install "kubectl-pvcmount"
      end
    end
    on_arm do
      url "https://github.com/Stenstromen/kubectl-pvcmount/releases/download/v1.0.0/kubectl-pvcmount_Darwin_arm64.tar.gz"
      sha256 "ec649ce5066acf98766b9e1c0aec6002a9c967be69cbe6862e257604fab54a2f"

      def install
        bin.install "kubectl-pvcmount"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Stenstromen/kubectl-pvcmount/releases/download/v1.0.0/kubectl-pvcmount_Linux_x86_64.tar.gz"
        sha256 "66b281b0ad8d754c86e85ec4935ce28ac8f74aefd830d70252f64373169335ca"

        def install
          bin.install "kubectl-pvcmount"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Stenstromen/kubectl-pvcmount/releases/download/v1.0.0/kubectl-pvcmount_Linux_arm64.tar.gz"
        sha256 "5944208e6127262898ebb1e88b5566c87fb149161419c5915b02a8b6d7c0d882"

        def install
          bin.install "kubectl-pvcmount"
        end
      end
    end
  end
end
