# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cask < Formula
  desc "Cloudflare ASK (CASK) is a Go binary for asking Cloudflare Workers AI (Llama 3.1 8B Instruct) for shell command suggestions, git command suggestions, or quick answers to general technical questions, straight from the terminal."
  homepage "https://github.com/Stenstromen/cask"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/cask/releases/download/v0.1.0/cask_Darwin_x86_64.tar.gz"
      sha256 "3d379462baa4b0ffab1e9f2ad24ee3edbf22e297daa4bc2d6437563a9884c9bf"

      define_method(:install) do
        bin.install "cask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Stenstromen/cask/releases/download/v0.1.0/cask_Darwin_arm64.tar.gz"
      sha256 "9ecddbb8a467ac5e85e5c69efb5966aabd76a8fa8137038e6df0bf5f62e1d4e0"

      define_method(:install) do
        bin.install "cask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Stenstromen/cask/releases/download/v0.1.0/cask_Linux_x86_64.tar.gz"
      sha256 "0b1910f100c8be669c2bb754f872c86829338b2b9dcb775bbb2a61c52c6a14d0"
      define_method(:install) do
        bin.install "cask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Stenstromen/cask/releases/download/v0.1.0/cask_Linux_arm64.tar.gz"
      sha256 "2f87bda17ab22f3150081d5ab0b843195e4e136503dd8b3afdb23fb11a0a3ae7"
      define_method(:install) do
        bin.install "cask"
      end
    end
  end
end
