# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godkimflare < Formula
  desc "Go binary for creating/updating DKIM records on Cloudflare."
  homepage "https://github.com/Stenstromen/godkimflare"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Stenstromen/godkimflare/releases/download/v1.1.1/godkimflare_Darwin_arm64.tar.gz"
      sha256 "5b2c7e071f0cb7ec9357fb90895f3a29699c4e082d0fafa037aba5fa40181b3b"

      def install
        bin.install "godkimflare"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/godkimflare/releases/download/v1.1.1/godkimflare_Darwin_x86_64.tar.gz"
      sha256 "df13557c3db3327fabc21b31eb9976de1b0672bc684b9c7e3c591d7bb7a6742e"

      def install
        bin.install "godkimflare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Stenstromen/godkimflare/releases/download/v1.1.1/godkimflare_Linux_arm64.tar.gz"
      sha256 "d35603d0f90ba1fe6afb5ab6a8b8e8fd72bb2a6075d30c7abd546084515aa699"

      def install
        bin.install "godkimflare"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/godkimflare/releases/download/v1.1.1/godkimflare_Linux_x86_64.tar.gz"
      sha256 "b12656dcb71821467ca23ec70a44a23e706997e34748d81b2ff2cab5f3549654"

      def install
        bin.install "godkimflare"
      end
    end
  end
end
