# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godkimflare < Formula
  desc "Go binary for creating/updating DKIM records on Cloudflare."
  homepage "https://github.com/Stenstromen/godkimflare"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/godkimflare/releases/download/v1.1.0/godkimflare_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "93ca15d6f2c226ea715cfd05939a63f10b828c671260d6410b2c24b1037803d4"

      def install
        bin.install "godkimflare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Stenstromen/godkimflare/releases/download/v1.1.0/godkimflare_1.1.0_Darwin_arm64.tar.gz"
      sha256 "300b28af69ffd35f9c3464e16f970a89b9dc3980c25e9cf9d240c2fd14681914"

      def install
        bin.install "godkimflare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/godkimflare/releases/download/v1.1.0/godkimflare_1.1.0_Linux_x86_64.tar.gz"
      sha256 "a4a7caeb982b840d4f0608037c511c0497ed7fb6397b32cfcbd14e35c107e569"

      def install
        bin.install "godkimflare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Stenstromen/godkimflare/releases/download/v1.1.0/godkimflare_1.1.0_Linux_arm64.tar.gz"
      sha256 "9dcb47cae3f43f05b23abf0590e950c007e54ff6e01a55d16d00535ef511d940"

      def install
        bin.install "godkimflare"
      end
    end
  end
end
