# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Godkimflare < Formula
  desc "Go binary for creating/updating DKIM records on Cloudflare."
  homepage "https://github.com/Stenstromen/godkimflare"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/godkimflare/releases/download/v1.0.0/godkimflare_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "80fb2071a84baeb622a84699e3e776fea8fe7145bd1f9574bf00d2bcec9a8c09"

      def install
        bin.install "godkimflare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Stenstromen/godkimflare/releases/download/v1.0.0/godkimflare_1.0.0_Darwin_arm64.tar.gz"
      sha256 "1517728dceb31cafe6a2c7e749aa042e563d10552a7aee024f7a60b00eaf5966"

      def install
        bin.install "godkimflare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/godkimflare/releases/download/v1.0.0/godkimflare_1.0.0_Linux_x86_64.tar.gz"
      sha256 "9cdd73ef44eddfca098d5bbeab79c65fa014123484451329bb30b36e714c3476"

      def install
        bin.install "godkimflare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Stenstromen/godkimflare/releases/download/v1.0.0/godkimflare_1.0.0_Linux_arm64.tar.gz"
      sha256 "339961a548da67cad8118525dec9abb36bf209202bfbe24cc2b526149d0b92a0"

      def install
        bin.install "godkimflare"
      end
    end
  end
end
