# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomtastsflare < Formula
  desc "Go binary for creating/updating MTA-STS records on Cloudflare, and create the accompanying Nginx configuration."
  homepage "https://github.com/Stenstromen/gomtastsflare"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/gomtastsflare/releases/download/v1.2.0/gomtastsflare_1.2.0_Darwin_x86_64.tar.gz"
      sha256 "0ae14d11ab53aa3d827c9c5e8e75fb225e9b3f5ebe6d41ac2adc515edab7f8b7"

      def install
        bin.install "gomtastsflare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Stenstromen/gomtastsflare/releases/download/v1.2.0/gomtastsflare_1.2.0_Darwin_arm64.tar.gz"
      sha256 "63a8351109f63e37ea604e75f0e10950ed8d6f8e132cfc8231b59953e55cfb3c"

      def install
        bin.install "gomtastsflare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/gomtastsflare/releases/download/v1.2.0/gomtastsflare_1.2.0_Linux_x86_64.tar.gz"
      sha256 "de6e645b63bc3b4e2ae8985016a44dfb7dc219c5435ed63eaac9525a595dc955"

      def install
        bin.install "gomtastsflare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Stenstromen/gomtastsflare/releases/download/v1.2.0/gomtastsflare_1.2.0_Linux_arm64.tar.gz"
      sha256 "0459da6a30ff8c449b82d81f2238a278956a9806e857c075a70f5662c54bebeb"

      def install
        bin.install "gomtastsflare"
      end
    end
  end
end
