# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gospfflare < Formula
  desc "Go binary for updating TLSA DANE record on cloudflare from x509 Certificate"
  homepage "https://github.com/Stenstromen/gospfflare"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/gospfflare/releases/download/v1.0.0/gospfflare_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "414a27d20edbcc5153a7af7a0d53589440abf0a2575bd8ad82e1e970ef1df4b3"

      def install
        bin.install "gospfflare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Stenstromen/gospfflare/releases/download/v1.0.0/gospfflare_1.0.0_Darwin_arm64.tar.gz"
      sha256 "92858cda7f4d02a212d254836b9ddf54aa00eeec1ed71b6005529edd74c93931"

      def install
        bin.install "gospfflare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/gospfflare/releases/download/v1.0.0/gospfflare_1.0.0_Linux_x86_64.tar.gz"
      sha256 "b0feab0b6955c5b78852287d695aab21cacb005e1d427615561f6bc1402ce0d0"

      def install
        bin.install "gospfflare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Stenstromen/gospfflare/releases/download/v1.0.0/gospfflare_1.0.0_Linux_arm64.tar.gz"
      sha256 "27f943c75be40a39fa6cb4eab2adf0dd27f691e7c7495a3d60071021a1cea851"

      def install
        bin.install "gospfflare"
      end
    end
  end
end
