# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gospfflare < Formula
  desc "Go binary for updating TLSA DANE record on cloudflare from x509 Certificate"
  homepage "https://github.com/Stenstromen/gospfflare"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Stenstromen/gospfflare/releases/download/v1.0.2/gospfflare_Darwin_arm64.tar.gz"
      sha256 "96f1d218f9cb9a1871df0d13ff1593c737c68a6be5ad86245ac60e0d5a4770ae"

      def install
        bin.install "gospfflare"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/gospfflare/releases/download/v1.0.2/gospfflare_Darwin_x86_64.tar.gz"
      sha256 "1d927739d4be1a7a23c00bfaff8ff2ef8a08e87c3673004c340326faf6c1306e"

      def install
        bin.install "gospfflare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/gospfflare/releases/download/v1.0.2/gospfflare_Linux_x86_64.tar.gz"
      sha256 "2eca218e2929a1964552d8992e6b61df8e81b862164a8ffd10293ce1900881e2"

      def install
        bin.install "gospfflare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Stenstromen/gospfflare/releases/download/v1.0.2/gospfflare_Linux_arm64.tar.gz"
      sha256 "139f8eb5c90941715b23f961f9be325b96838b542c1a33648efdc98c6fcbc1f0"

      def install
        bin.install "gospfflare"
      end
    end
  end
end
