# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotlsaflare < Formula
  desc "Go binary for updating TLSA DANE record on cloudflare from x509 Certificate"
  homepage "https://github.com/Stenstromen/gotlsaflare"
  version "2.8.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/gotlsaflare/releases/download/v2.8.2/gotlsaflare_Darwin_x86_64.tar.gz"
      sha256 "7b48e89aa892036e9605fbd6bac49651fae685bf1e5b68133eee0aafde2f3984"

      def install
        bin.install "gotlsaflare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Stenstromen/gotlsaflare/releases/download/v2.8.2/gotlsaflare_Darwin_arm64.tar.gz"
      sha256 "0a72e796caf607c683d37f945e8216870d5ca396a4a7fb4f647937a80da73c46"

      def install
        bin.install "gotlsaflare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Stenstromen/gotlsaflare/releases/download/v2.8.2/gotlsaflare_Linux_x86_64.tar.gz"
      sha256 "83cfc020fdfd2fc205674bd8b60b6f9ef4045613272be975186a33dfd682a669"
      def install
        bin.install "gotlsaflare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Stenstromen/gotlsaflare/releases/download/v2.8.2/gotlsaflare_Linux_arm64.tar.gz"
      sha256 "fa49a49908b60a917e1feb99071e21174f7a66f0edd28f606eb18beaf53c8f0d"
      def install
        bin.install "gotlsaflare"
      end
    end
  end
end
