# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotlsaflare < Formula
  desc "Go binary for updating TLSA DANE record on cloudflare from x509 Certificate"
  homepage "https://github.com/Stenstromen/gotlsaflare"
  version "2.7.0-test.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/gotlsaflare/releases/download/v2.7.0-test.3/gotlsaflare_Darwin_x86_64.tar.gz"
      sha256 "a9a009258d25c7f0e1c5a2446bbaf666263fd7177ce0c5557b912fc11db48d02"

      def install
        bin.install "gotlsaflare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Stenstromen/gotlsaflare/releases/download/v2.7.0-test.3/gotlsaflare_Darwin_arm64.tar.gz"
      sha256 "c17bf3fccc563ca468b0b8ebc412c6cde0232cc99c1f6bb7bb8b14b3a0637044"

      def install
        bin.install "gotlsaflare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Stenstromen/gotlsaflare/releases/download/v2.7.0-test.3/gotlsaflare_Linux_x86_64.tar.gz"
        sha256 "531878279c4a641d05fee6a06564c1474dc7909436bb442187ae67516428d69c"

        def install
          bin.install "gotlsaflare"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Stenstromen/gotlsaflare/releases/download/v2.7.0-test.3/gotlsaflare_Linux_arm64.tar.gz"
        sha256 "8220b63df66877f7c5293978f9d544facb445efb4afe09480d68be12780f52a3"

        def install
          bin.install "gotlsaflare"
        end
      end
    end
  end
end
