# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipcalc < Formula
  desc "Go binary for IPv4/IPv6 subnet calculator"
  homepage "https://github.com/Stenstromen/ipcalc"
  version "0.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/goipcalc/releases/download/v0.0.0/ipcalc_Darwin_x86_64.tar.gz"
      sha256 "1094400d155204d142c17a044bcc50febfdf93c4967ad8075c472c3f9e626f7a"

      def install
        bin.install "ipcalc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Stenstromen/goipcalc/releases/download/v0.0.0/ipcalc_Darwin_arm64.tar.gz"
      sha256 "c6fc1d6c8716d6fb4764498f45a1a4c3d3281185ec8d4eae23b62d2cca9339b9"

      def install
        bin.install "ipcalc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Stenstromen/goipcalc/releases/download/v0.0.0/ipcalc_Linux_x86_64.tar.gz"
      sha256 "644c4bc18ac7dfbbafe68ab575d0e79c0f26cf3fbb4bff39de0c0a976e98e70a"
      def install
        bin.install "ipcalc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Stenstromen/goipcalc/releases/download/v0.0.0/ipcalc_Linux_arm64.tar.gz"
      sha256 "6207e752106222b62defe8005dd723cd40bda801bcff5c84deb988d744cd6f87"
      def install
        bin.install "ipcalc"
      end
    end
  end
end
