# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlMscale < Formula
  desc "Scale resources across multiple namespaces"
  homepage "https://github.com/Stenstromen/kubectl-mscale"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/kubectl-mscale/releases/download/v0.0.1/kubectl-mscale_Darwin_x86_64.tar.gz"
      sha256 "470a4c94ec7a462716fff5bb8bbce5c22887848dbf9d11f3064c3de29bed1df3"

      def install
        bin.install "kubectl-mscale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Stenstromen/kubectl-mscale/releases/download/v0.0.1/kubectl-mscale_Darwin_arm64.tar.gz"
      sha256 "77fcbeadda1dfed3e2a29b4166a3b6ddcf7b5ca606ed9adc2a0a72f451d65657"

      def install
        bin.install "kubectl-mscale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Stenstromen/kubectl-mscale/releases/download/v0.0.1/kubectl-mscale_Linux_x86_64.tar.gz"
      sha256 "505bb9e6c3a68f038c699d4dc4bccc2fa3198cdc2c6938e4d3caa8d795b1344a"
      def install
        bin.install "kubectl-mscale"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Stenstromen/kubectl-mscale/releases/download/v0.0.1/kubectl-mscale_Linux_arm64.tar.gz"
      sha256 "67bdd3f0633e9df511eb842764891185fdc6155c2adde987e8aed6d704a6a7f1"
      def install
        bin.install "kubectl-mscale"
      end
    end
  end
end
