# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlPvcmount < Formula
  desc "Go binary for temporary mounting of PVCs"
  homepage "https://github.com/Stenstromen/kubectl-pvcmount"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/Stenstromen/kubectl-pvcmount/releases/download/v1.0.0/kubectl-pvcmount_Darwin_x86_64.tar.gz"
      sha256 "212de03db18b246bd271dbe86e19e711613dbf0d6e51369da72295f082abb0dd"

      def install
        bin.install "kubectl-pvcmount"
      end
    end
    on_arm do
      url "https://github.com/Stenstromen/kubectl-pvcmount/releases/download/v1.0.0/kubectl-pvcmount_Darwin_arm64.tar.gz"
      sha256 "1c30b49bc15c7d45d29a8db66479e954c50c3d31684ed9470cf4fba61d1ddc1a"

      def install
        bin.install "kubectl-pvcmount"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Stenstromen/kubectl-pvcmount/releases/download/v1.0.0/kubectl-pvcmount_Linux_x86_64.tar.gz"
        sha256 "5dbb1c9124cc10fac46c4ade2618135d39c7c58c1d4c62e12708736a91d55283"

        def install
          bin.install "kubectl-pvcmount"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Stenstromen/kubectl-pvcmount/releases/download/v1.0.0/kubectl-pvcmount_Linux_arm64.tar.gz"
        sha256 "9cf080836166a8963018c21848cc1d19d94a5f1f2cdb54013d73654546404019"

        def install
          bin.install "kubectl-pvcmount"
        end
      end
    end
  end
end
