# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ncregistry < Formula
  desc "The NcRegistry Go binary is a powerful command-line tool designed to streamline interaction with Docker registries"
  homepage "https://github.com/Stenstromen/ncregistry"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/ncregistry/releases/download/v1.0.0/ncregistry_Darwin_x86_64.tar.gz"
      sha256 "c40f62232e136779b05c28daaba5728c992f4ebc0a4b5b2286db1e853d3425eb"

      def install
        bin.install "ncregistry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Stenstromen/ncregistry/releases/download/v1.0.0/ncregistry_Darwin_arm64.tar.gz"
      sha256 "c215f2ed6deda50ba110fba366e1251b418c3df8f41c4bbb86f4851add80e039"

      def install
        bin.install "ncregistry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Stenstromen/ncregistry/releases/download/v1.0.0/ncregistry_Linux_x86_64.tar.gz"
      sha256 "c3528c188ae5d9fef34977c281253853822944e73e6f958f82f01c4485f8e752"

      def install
        bin.install "ncregistry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Stenstromen/ncregistry/releases/download/v1.0.0/ncregistry_Linux_arm64.tar.gz"
      sha256 "f64933dba23df78358b05245506f5647b2ac77c3a8825c9736e2622b925ed343"

      def install
        bin.install "ncregistry"
      end
    end
  end
end
